### PR TITLE
[SDVX] Change ap_card and submonitor_bg jpeg to denoised png

### PR DESCRIPTION
**Pull request by amane-ame**
All pngs have been compressed by FileOptimizer.

### CODE REVIEW

**Comment by dannylin0711** [comment]
Instead of uploading the files to this repo, the plugin structure would change to specify user directory and get assets from the game, webui won't preload with these files in the future.

**Comment by amane-ame** [comment]
So when will be the future…? Is there a planned releasing time point?在 2022年6月7日，18:13，LatoWolf ***@***.***> 写道：﻿
Instead of uploading the files to this repo, the plugin structure would change to specify user directory and get assets from the game, webui won't preload with these files in the future.

**Comment by dannylin0711** [comment]
Not sure yet, plus asphyxia not yet fully complete with new API Freddie is making right now, so we'll have to wait.

**Comment by TsFreddie** [comment]
We don't know. I've tried to make filesystem access in CORE which didn't turn out to be convenient or sensible.

Another idea is to just upload them in a CDN and load them over the air, but that would partially defeat the offline nature of plugins. Maybe a toggle and a warning would work. (Do note that CDN access can track users, like email images do, which isn't ideal for some people.)

Either way I'm not convinced to make plugins three times bigger just to get some better images in WebUI.

**Comment by dannylin0711** [comment]
That's why I try to reduce the size with smaller dimension jpgs instead of using compressed pngs, and yes, I would rather try not to make those assets any bigger,

**Comment by anjing-puteh** [comment]
getting the images (except for the skill level) should be fine but it's not going to be easy for options like custom bgm because it's a .s3p file.

**Pull request closed without merging**
